- hosts: localhost
  connection: local
  become: true
  
  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False
      
  tasks:
    - include: tasks/tweaks.yml
    - include: tasks/packages.yml
    - include: tasks/packages_pip.yml
    - include: tasks/software_flatpak.yml
    - include: tasks/files.yml
    - include: tasks/repos.yml
