- name: copy wallpaper from local directory
  copy:
    remote_src: true
    src: "{{ item }}"
    dest: /home/jeremy/.local/share/backgrounds
    owner: jeremy
    group: jeremy
  with_fileglob:
    - "/home/jeremy/Pictures/Wallpapers/default/*.png"

- name: copy .bashrc file
  copy:
    src: files/bashrc
    dest: /home/jeremy/.bashrc
    owner: jeremy
    group: jeremy

- name: create .bash directory if it does not exist
  file:
    path: /home/jeremy/.bash
    state: directory
    owner: jeremy
    group: jeremy
    mode: '0700'

- name: copy bash include file to .bash directory
  copy:
    src: files/bashrc_extra
    dest: /home/jeremy/.bash/bashrc_extra
    owner: jeremy
    group: jeremy

- name: Ansible check directory.
  stat:
    path: /home/jeremy/.themes
  register: my_folder

- name: "echo if directory already existed"
  debug:
    msg: "the .themes directory is already existed"
  when: my_folder.stat.exists

- name: "Ansible Create directory if not exists"
  file:
    path: /home/jeremy/.themes
    state: directory
    mode: 0755
    group: jeremy
    owner: jeremy
  when: my_folder.stat.exists == false