- name: copy wallpaper from local directory
  copy:
    remote_src: true
    src: "{{ item }}"
    dest: /usr/share/backgrounds/pop
    owner: root
    group: root
  with_fileglob:
    - "/home/jeremy/Pictures/Wallpapers/default/*.png"
    
- name: copy .bashrc file
  copy:
    src: files/bashrc
    dest: /home/jeremy/.bashrc
    owner: jeremy
    group: jeremy
