- name: system setup | apt packages | install
  apt:
    name: 
      - htop
      - inxi # Command line system information script for console
      - curl
      - neofetch
      - rsync
      - wget
      - gnome-tweaks
      - caffeine
      - python3-pip # python package for running pip
      - python3-psutil
      - cifs-utils # needed for smb share
      - zfsutils-linux # needed for zfs support on pop
      - micro
      - alacritty
      -zsh
