- name: system setup | apt packages | install
  apt:
    name: 
      - htop
      - inxi # Command line system information script for console
      - curl
      - neofetch
      - rsync
      - wget
      - gnome-tweaks
      - caffeine
      - python3-pip # python package for running pip
      - python3-psutil
      - python3-apt # for adding repos to apt
      - gpg
      - cifs-utils # needed for smb share
      - zfsutils-linux # needed for zfs support on pop
      - micro
      - alacritty
      - zsh
      - ranger # terminal file manager
      - mc # midnight commander terminal file manager
      - exfatprogs #replaces exfat-utils

- name: software | remove unneeded workstation packages on debian and ubuntu hosts
  tags: cleanup,packages,workstation-packages
  package:
    state: absent
    name:
      - libreoffice-base-core
      - libreoffice-calc
      - libreoffice-common
      - libreoffice-core
      - libreoffice-draw
      - libreoffice-gnome
      - libreoffice-gtk3
      - libreoffice-impress
      - libreoffice-math
      - libreoffice-writer
  when: ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]